[package]
edition = "2021"
name = "sabi"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[dependencies]
sabi_derive = {path = "../sabi_derive"}

bevy_atmosphere = "0.3.0"
#bevy_rapier3d = {version = "0.14", features = ["serde-serialize"]}
bevy_rapier3d = {version = "0.14", git = "https://github.com/aceeri/bevy_rapier", branch = "serialize-joints", features = ["serde-serialize"]}
bevy_renet = {git = "https://github.com/lucaspoffo/renet"}
bincode = "1.3.3"
derive_more = "0.99.17"
fixed = {version = "1.11.0", features = ["serde", "std", "serde-str"]}
fxhash = "0.2.1"
igd = "0.12.0"
iyes_loopless = {version = "0.5.1", features = ["states"]}
lazy_static = "1.4"
my_internet_ip = "0.1.1"
rand = "0.8"
serde = "1.0.136"
smallvec = "1.7.0"
smolset = "1.3.1"
vec-collections = "0.4.3"
wgpu-types = "0.12"
zstd = "0.11.2"

[dependencies.bevy]
default-features = false
version = "0.7.0"
#path = "../bevy"
