[package]
categories = ["game-engines", "networking"]
description = "A client-server networking architecture for bevy."
edition = "2021"
keywords = ["networking", "client server architecture", "prediction", "games", "bevy"]
license = "MIT OR Apache-2.0"
name = "sabi"
readme = "../README.md"
repository = "https://github.com/aceeri/sabi"
version = "0.2.0"

[lib]
path = "src/lib.rs"

[dependencies]
sabi_derive = {path = "../sabi_derive"}

bevy_rapier3d = {version = "0.14", features = ["serde-serialize"]}
bevy_renet = {git = "https://github.com/lucaspoffo/renet"}
bincode = "1.3"
derive_more = "0.99"
fixed = {version = "1.11", features = ["serde", "std", "serde-str"]}
fxhash = "0.2.1"
igd = "0.12.0"
iyes_loopless = {version = "0.6.0", features = ["states"]}
lazy_static = "1.4"
my_internet_ip = "0.1.1"
rand = "0.8"
serde = "1"
smallvec = "1.7"
smolset = "1.3"
toml = "0.5"
vec-collections = "0.4"
wgpu-types = "0.13"
zstd = {version = "0.11", features = ["zdict_builder"]}

[dependencies.bevy]
default-features = false
version = "0.7.0"
#path = "../bevy"
